#!/bin/bash
# Quick Start Guide for Enhanced Attendance System

clear
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║        ENHANCED ATTENDANCE SYSTEM - QUICK START              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

echo "🚀 MAIN LAUNCHER (Recommended)"
echo "════════════════════════════════════════════════════════════"
echo "  ./start_attendance.sh    - Auto-detects WiFi, runs best mode"
echo ""

echo "🌐 WEB INTERFACE"
echo "════════════════════════════════════════════════════════════"
echo "  ./run_web.sh             - Flask web interface"
echo "                             Access: http://localhost:5000"
echo ""

echo "🖥️  GUI APPLICATION"
echo "════════════════════════════════════════════════════════════"
echo "  ./run_app.sh             - Desktop GUI (requires display)"
echo ""

echo "📷 OFFLINE MODE"
echo "════════════════════════════════════════════════════════════"
echo "  ./run_offline.sh         - Camera + display (no WiFi needed)"
echo ""

echo "🧪 TESTING & DEMOS"
echo "════════════════════════════════════════════════════════════"
echo "  ./run_enhanced_test.sh   - Test User IDs & monthly summaries"
echo "  ./test_lcd5110_simple.py - Test Nokia LCD 5110 display"
echo ""

echo "📊 NEW FEATURES"
echo "════════════════════════════════════════════════════════════"
echo "  ✓ Random User IDs (e.g., USR95B0D692)"
echo "  ✓ User Directory Excel sheet (first tab)"
echo "  ✓ Auto-assign ID on face enrollment"
echo "  ✓ Monthly calendar with all days pre-filled"
echo "  ✓ Automatic monthly summary:"
echo "    • Total working days"
echo "    • Total hours worked"
echo "    • Days late + total late time"
echo "    • Days with OT + total overtime"
echo "  ✓ Per-user monthly Excel sheets"
echo "  ✓ User ID in all records and logs"
echo ""

echo "📁 OUTPUT FILES"
echo "════════════════════════════════════════════════════════════"
echo "  data/attendance.xlsx     - Main attendance file"
echo "                             • User Directory (first sheet)"
echo "                             • One sheet per user per month"
echo "  data/user_ids.csv        - User ID mappings"
echo "  data/status_log.csv      - Status change log with IDs"
echo ""

echo "📖 DOCUMENTATION"
echo "════════════════════════════════════════════════════════════"
echo "  ENHANCED_FEATURES.md     - Complete feature documentation"
echo "  EXCEL_FORMAT_GUIDE.md    - Excel format explanation"
echo "  OFFLINE_MODE.md          - Offline mode guide"
echo ""

echo "💡 QUICK TIPS"
echo "════════════════════════════════════════════════════════════"
echo "  • Each user gets a unique ID automatically"
echo "  • Monthly summaries update after each check-in/out"
echo "  • Late = after 8:30 AM (red)"
echo "  • On Time = before 8:30 AM (green)"
echo "  • Overtime = after 5:00 PM (orange)"
echo "  • Weekends highlighted in gray"
echo ""

echo "🎯 TYPICAL USAGE"
echo "════════════════════════════════════════════════════════════"
echo "  1. Run: ./start_attendance.sh"
echo "  2. System detects WiFi and chooses mode"
echo "  3. Users check in/out with face recognition"
echo "  4. View Excel file for monthly reports"
echo "  5. Each user's sheet shows:"
echo "     - Daily attendance"
echo "     - Monthly summary at bottom"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "Ready to start? Run: ./start_attendance.sh"
echo "═══════════════════════════════════════════════════════════"
echo ""
